language: android
android:
  components:
    - build-tools-21.1.1
    - android-21
    - add-on-google-apis-google-19
    - extra-google-google_play_services
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'