# configuration for https://travis-ci.org/mapsforge/mapsforge
sudo: true
language: android
jdk:
  - openjdk8
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
script: ./gradlew clean build