language: android
android:
  components:
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - tools
    - build-tools-23.0.2
    - android-23
  licenses:
    - '.+'
script: ./gradlew assembleRelease