#travis ci

language: android
android:
  components:
    - extra-android-support
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
script: ./gradlew assembleDebug

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python2.7
  - chmod +x gradlew