language: android
android:
  components:
    - build-tools-23.0.2
    - android-23
    - sys-img-x86-android-tv-l
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'